### ISSUE TITLE
Possible improvements to the script

### ISSUE THREAD

**Issue by anakin87** [cognitivecomputations/spectrum#5]
I'm taking my first steps with Spectrum. Great work!

I find it difficult to run it on notebooks, mostly because of `prompt_toolkit`, but I understand it is convenient, especially for weights selection.

However, I believe the script could benefit from a couple of improvements:
- make it possible to import it (in notebooks), by wrapping the final section in a `if __name__ == "__main__":` block
- It seems that `self.optimizer` and `self.tokenizer` are initialized but never actually used.

@Crystalcareai What do you think?
If these observations make sense, I'd be more than happy to open a PR to address them.

**Comment by Crystalcareai** [comment]
wonderful suggestions, and I needed to tidy up the code anyway. All changes can be found here: https://github.com/cognitivecomputations/spectrum/pull/6

**Comment by anakin87** [comment]
Great. Thanks!
